version: "3"
vars:
  GOEXE: '{{ .GOEXE | default "go"}}'
  PROVIDER_VERSION: '{{ .PROVIDER_VERSION | default "2.30.2"}}'
tasks:
  build: 
    vars:
      flags: ""
    cmds:
      - "{{ .GOEXE }} build -o terraform-provider-bitbucket_v{{ .PROVIDER_VERSION }} {{ .flags }}"
